@startmindmap
* ノックリモコン
** 操作対象
*** スマートホーム
**** エアコン
**** テレビ
**** ストーブ
**** ステレオ
**** 照明
*** スマートファクトリー
*** スマートカー
*** スマートホーム
** 必要性
*** 障がい者(発声障がい)
***[#Orange] 環境(発声が制限される)
****[#Orange] テレワーク
****[#Orange] 静粛な場所
*****[#Orange] 葬儀場
***** …
** どういうときにノック？
*** プライバシー
*** ドアノック
**** 面談(何回が適切？)
**** トイレ
*** 呼び出し(失礼w)
** 原理
*** 圧電ブザー
**** 振動・打撃
*****[#lightgreen] リズミカル
******[#lightgreen] 雨のしずく 
******[#lightgreen] コーヒーのドリップ 
******[#lightgreen] 焼肉(脂が落ちる) 
*******[#lightgreen] ひとりキャンプ？
**** 地震計
**** ヘルスメーター

left side

** 競合
*** 指パッチン
*** スマートスピーカー(音声認識)
*** 顔画像認識
*** 呼び出しベル
*** カメラシャッターボタン(Daiso ￥300/個)
*** Amazon Dashボタン
** メリット
*** 照合が簡単
**** 応答が早い
**** 通信コストが安い
** デメリット
*** 個人特定ができない
*** 複雑な操作に向かない
** データ収集
***[#LightBlue] ノック回数=使用回数
***[#LightBlue] 叩いた場所、もの
***[#LightBlue] ノックスピード・間隔
****[#LightBlue] 心理状況(あせり？)
@endmindmap